### ISSUE TITLE
Remove device name releasetools script 

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_a3-common#2]
This isn't a3 specific, and concerns all devices. Since the props that are fixed by the script are all set by libinit at boot, the script is redundant, so it should be removed from all device common repos

**Comment by vlw** [comment]
This script is fixing build prop lines only is this lines are exists. I guess we're need to keep this file. For example, if somebody want to make MIUI Patchrom, MIUI scripts will read device info only from build.prop

**Comment by vzvikaramba** [comment]
Well, then that's that person's issue, not ours. I made the scripts for fixing up names on unified builds way before los made overriding the props the default solution in libinit, so in that respect, the script is redundant. The script being gone shouldn't affect the purpose you stated above, if at all, and if it does, is not our concern.

**Comment by vzvikaramba** [comment]
@minz1, any thoughts?

**Comment by minz1** [comment]
There is no way we should ever make decisions based on what MIUI patchrom requires. Removing it should be fine

**Comment by vlw** [comment]
@minz1 Ah, ok, u can remove it
