### ISSUE TITLE
Remove product/qcom-bt.mk

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_a3-common#4]
Most of the things here are already specified in msm8916-common (all the devices have Bluetooth). 

The ones that aren't are redunant props, and need to be removed anyways.

**Comment by vlw** [comment]
This file is needed
It contain only one line
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/samsung/a3-common/bluetooth
